blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/hugo-next/hugo-theme-next/discussions/categories/q-a
    about: 请在此处提问或回答问题(Please ask and answer questions here)